import { defineField, defineType } from "sanity";

export const productType = defineType({
  name: "product",
  title: "Produtos",
  type: "document",
  fieldsets: [
    { name: "basic", title: "Informações básicas", options: { columns: 2 } },
    { name: "images", title: "Imagens" },
    { name: "descriptions", title: "Descrições" },
    { name: "siteDisplay", title: "Exibição no site", options: { columns: 2 } },
    { name: "details", title: "Detalhes do produto", options: { columns: 2 } },
    { name: "status", title: "Status do cadastro" },
  ],
  fields: [
    defineField({
      name: "name",
      title: "Nome do produto",
      type: "string",
      description: "Nome que aparece no card e na página do produto.",
      fieldset: "basic",
      validation: (rule) => rule.required().min(2),
    }),
    defineField({
      name: "slug",
      title: "Link do produto",
      type: "slug",
      description: "Endereço do produto no site (gerado a partir do nome).",
      fieldset: "basic",
      options: { source: "name", maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "category",
      title: "Categoria",
      type: "reference",
      description: "Categoria usada no filtro e na organização dos produtos.",
      fieldset: "basic",
      to: [{ type: "category" }],
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "price",
      title: "Preço",
      type: "number",
      description: "Preço de venda (somente número, sem R$).",
      fieldset: "basic",
      validation: (rule) => rule.required().positive(),
    }),
    defineField({
      name: "mainImage",
      title: "Imagem principal",
      type: "image",
      description: "Imagem usada no card do produto e na página individual.",
      fieldset: "images",
      validation: (rule) => rule.required(),
      options: { hotspot: true },
      fields: [
        defineField({
          name: "alt",
          title: "Texto alternativo da imagem",
          type: "string",
          description: "Descrição curta da imagem para acessibilidade.",
        }),
      ],
    }),
    defineField({
      name: "shortDescription",
      title: "Descrição curta",
      type: "text",
      rows: 3,
      description: "Texto que aparece no card do produto.",
      fieldset: "descriptions",
      validation: (rule) => rule.required().max(240),
    }),
    defineField({
      name: "longDescription",
      title: "Descrição completa",
      type: "text",
      rows: 6,
      description: "Texto exibido na página individual do produto.",
      fieldset: "descriptions",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "material",
      title: "Material",
      type: "string",
      description: "Informação de material mostrada no detalhe do produto.",
      fieldset: "details",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "size",
      title: "Tamanho",
      type: "string",
      description: "Informação de tamanho exibida no detalhe do produto.",
      fieldset: "details",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "visualKind",
      title: "Estilo visual",
      type: "string",
      description: "Usado para manter o estilo visual consistente no site.",
      fieldset: "siteDisplay",
      options: {
        list: [
          { title: "Rosa", value: "rose" },
          { title: "Coração", value: "heart" },
          { title: "Estrela", value: "star" },
          { title: "Folha", value: "leaf" },
        ],
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "novelty",
      title: "Produto novidade",
      type: "boolean",
      description: "Marque para destacar este produto como novidade.",
      fieldset: "siteDisplay",
      initialValue: false,
    }),
    defineField({
      name: "featured",
      title: "Produto em destaque",
      type: "boolean",
      description: "Marque para mostrar este produto em destaque na home.",
      fieldset: "siteDisplay",
      initialValue: false,
    }),
    defineField({
      name: "available",
      title: "Disponível para venda",
      type: "boolean",
      description: "Desmarque se o produto estiver indisponível no momento.",
      fieldset: "siteDisplay",
      initialValue: true,
    }),
    defineField({
      name: "archived",
      title: "Arquivar este produto",
      type: "boolean",
      fieldset: "status",
      description:
        "Marque para ocultar este produto do site sem excluir o cadastro. Use quando quiser pausar a exibição.",
      initialValue: false,
    }),
  ],
  preview: {
    select: {
      title: "name",
      subtitle: "category.name",
      media: "mainImage",
      archived: "archived",
    },
    prepare: ({ title, subtitle, media, archived }) => ({
      title,
      subtitle: archived
        ? `Arquivado · ${subtitle ? `Categoria: ${subtitle}` : "Sem categoria"}`
        : subtitle
          ? `Categoria: ${subtitle}`
          : "Sem categoria",
      media,
    }),
  },
});
