import { defineField, defineType } from "sanity";

export const siteSettingsType = defineType({
  name: "siteSettings",
  title: "Configurações do site",
  type: "document",
  fieldsets: [
    { name: "seo", title: "SEO" },
    { name: "brand", title: "Marca e topo" },
    { name: "navigation", title: "Navegação" },
    { name: "about", title: "Seção Sobre" },
    { name: "contact", title: "Contato" },
  ],
  fields: [
    defineField({
      name: "seo",
      title: "SEO (estrutura principal)",
      type: "object",
      fieldset: "seo",
      description: "Dados de SEO usados na metadata global do site.",
      fields: [
        defineField({
          name: "title",
          title: "Título SEO",
          type: "string",
          description: "Título que aparece no Google e na aba do navegador.",
          validation: (rule) => rule.required(),
        }),
        defineField({
          name: "description",
          title: "Descrição SEO",
          type: "text",
          rows: 3,
          description: "Resumo que aparece nos resultados de busca.",
          validation: (rule) => rule.required(),
        }),
      ],
    }),
    defineField({
      name: "seoTitle",
      title: "Título SEO (campo simples)",
      type: "string",
      fieldset: "seo",
      description: "Alternativa simples ao campo SEO estruturado.",
    }),
    defineField({
      name: "seoDescription",
      title: "Descrição SEO (campo simples)",
      type: "text",
      rows: 3,
      fieldset: "seo",
      description: "Alternativa simples ao campo SEO estruturado.",
    }),
    defineField({
      name: "ogImage",
      title: "Imagem de compartilhamento",
      type: "image",
      fieldset: "seo",
      description: "Imagem usada quando o link do site é compartilhado (WhatsApp/Instagram).",
      options: { hotspot: true },
      fields: [
        defineField({
          name: "alt",
          title: "Texto alternativo",
          type: "string",
        }),
      ],
    }),
    defineField({
      name: "heroTitle",
      title: "Título principal (hero)",
      type: "string",
      fieldset: "brand",
      description: "Texto principal exibido no centro do topo da página.",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "heroSubtitle",
      title: "Subtítulo principal (hero)",
      type: "string",
      fieldset: "brand",
      description: "Texto menor abaixo do título principal no hero.",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "heroNote",
      title: "Linha de apoio do hero",
      type: "string",
      fieldset: "brand",
      description: "Frase curta de apoio que aparece no hero.",
    }),
    defineField({
      name: "brandTagline",
      title: "Tagline da marca",
      type: "string",
      fieldset: "brand",
      description: "Texto curto exibido no header, abaixo do nome da marca.",
    }),
    defineField({
      name: "navItems",
      title: "Links do menu",
      type: "array",
      fieldset: "navigation",
      description: "Itens de navegação do menu principal (desktop e mobile).",
      of: [
        defineField({
          name: "item",
          title: "Item do menu",
          type: "object",
          fields: [
            defineField({
              name: "id",
              title: "Identificador interno (opcional)",
              type: "string",
              description: "Não aparece no site. Serve para organização técnica.",
            }),
            defineField({
              name: "label",
              title: "Texto do menu",
              type: "string",
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: "href",
              title: "Link do menu",
              type: "string",
              description: "Exemplo: #produtos, #contato",
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: "cta",
              title: "Botão de destaque",
              type: "boolean",
              description: "Marque se este item deve aparecer como botão destacado.",
              initialValue: false,
            }),
          ],
        }),
      ],
    }),
    defineField({
      name: "aboutText",
      title: "Texto da seção Sobre",
      type: "text",
      rows: 4,
      fieldset: "about",
      description: "Texto principal exibido na seção Sobre.",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "aboutCards",
      title: "Cards da seção Sobre",
      type: "array",
      fieldset: "about",
      description: "Blocos de conteúdo exibidos na seção Sobre.",
      of: [
        defineField({
          name: "card",
          title: "Card",
          type: "object",
          fields: [
            defineField({
              name: "title",
              title: "Título do card",
              type: "string",
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: "description",
              title: "Descrição do card",
              type: "text",
              rows: 3,
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: "tone",
              title: "Cor de destaque do card",
              type: "string",
              options: {
                list: [
                  { title: "Padrão", value: "default" },
                  { title: "Rosa", value: "pink" },
                  { title: "Verde", value: "green" },
                ],
              },
            }),
          ],
        }),
      ],
    }),
    defineField({
      name: "aboutPills",
      title: "Pílulas da seção Sobre",
      type: "array",
      fieldset: "about",
      description: "Frases curtas de apoio da seção Sobre.",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "whatsapp",
      title: "WhatsApp",
      type: "string",
      fieldset: "contact",
      description: "Número com DDI/DDD. Exemplo: 5561999999999",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "instagram",
      title: "Instagram",
      type: "url",
      fieldset: "contact",
      description: "Link completo do Instagram da marca.",
      validation: (rule) => rule.uri({ scheme: ["http", "https"] }),
    }),
    defineField({
      name: "location",
      title: "Local de atendimento",
      type: "string",
      fieldset: "contact",
      description: "Texto exibido no bloco principal de contato.",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "contactDescription",
      title: "Descrição de contato",
      type: "text",
      rows: 4,
      fieldset: "contact",
      description: "Texto de apoio na seção de contato.",
    }),
    defineField({
      name: "contactActions",
      title: "Ações de contato",
      type: "array",
      fieldset: "contact",
      description: "Botões e mensagens exibidos no bloco de contato.",
      of: [
        defineField({
          name: "action",
          title: "Ação",
          type: "object",
          fields: [
            defineField({
              name: "label",
              title: "Texto do botão/linha",
              type: "string",
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: "href",
              title: "Link (opcional)",
              type: "string",
              description: "Se vazio, vira uma linha apenas informativa.",
            }),
            defineField({
              name: "messageOnly",
              title: "Somente mensagem",
              type: "boolean",
              description: "Marque quando não houver link clicável.",
              initialValue: false,
            }),
          ],
        }),
      ],
    }),
    defineField({
      name: "contactMainCtaText",
      title: "Texto do botão principal",
      type: "string",
      fieldset: "contact",
      description: "Texto do botão principal da seção de contato.",
    }),
    defineField({
      name: "contactFloatingText",
      title: "Texto do botão flutuante",
      type: "string",
      fieldset: "contact",
      description: "Texto do botão flutuante de WhatsApp.",
    }),
  ],
  preview: {
    prepare: () => ({
      title: "Configurações do site",
      subtitle: "Textos globais, contato, navegação e SEO",
    }),
  },
});
