import { defineField, defineType } from "sanity";

export const siteSettingsType = defineType({
  name: "siteSettings",
  title: "Configurações do site",
  type: "document",
  fieldsets: [
    { name: "seo", title: "SEO" },
    { name: "brand", title: "Marca e topo" },
    { name: "contact", title: "Contato" },
  ],
  fields: [
    defineField({
      name: "seo",
      title: "SEO (estrutura principal)",
      type: "object",
      fieldset: "seo",
      description: "Dados de SEO usados na metadata global do site.",
      fields: [
        defineField({
          name: "title",
          title: "Título SEO",
          type: "string",
          description: "Título que aparece no Google e na aba do navegador.",
          validation: (rule) => rule.required(),
        }),
        defineField({
          name: "description",
          title: "Descrição SEO",
          type: "text",
          rows: 3,
          description: "Resumo que aparece nos resultados de busca.",
          validation: (rule) => rule.required(),
        }),
      ],
    }),
    defineField({
      name: "seoTitle",
      title: "Título SEO (campo simples)",
      type: "string",
      fieldset: "seo",
      description: "Alternativa simples ao campo SEO estruturado.",
    }),
    defineField({
      name: "seoDescription",
      title: "Descrição SEO (campo simples)",
      type: "text",
      rows: 3,
      fieldset: "seo",
      description: "Alternativa simples ao campo SEO estruturado.",
    }),
    defineField({
      name: "ogImage",
      title: "Imagem de compartilhamento",
      type: "image",
      fieldset: "seo",
      description: "Imagem usada quando o link do site é compartilhado (WhatsApp/Instagram).",
      options: { hotspot: true },
      fields: [
        defineField({
          name: "alt",
          title: "Texto alternativo",
          type: "string",
        }),
      ],
    }),
    defineField({
      name: "headerTitle",
      title: "Título principal do header (texto)",
      type: "string",
      fieldset: "brand",
      description:
        "Texto principal do topo do site. Use quando não quiser usar imagem como logo.",
    }),
    defineField({
      name: "headerLogo",
      title: "Logo do header (imagem opcional)",
      type: "image",
      fieldset: "brand",
      description:
        "Se enviar uma imagem, ela será usada no lugar do texto no título principal do header.",
      options: { hotspot: true },
      fields: [
        defineField({
          name: "alt",
          title: "Texto alternativo da logo",
          type: "string",
          description: "Descrição da logo para acessibilidade.",
        }),
      ],
    }),
    defineField({
      name: "heroTitle",
      title: "Título principal (hero)",
      type: "string",
      fieldset: "brand",
      description: "Texto principal exibido no centro do topo da página.",
    }),
    defineField({
      name: "heroSubtitle",
      title: "Subtítulo principal (hero)",
      type: "string",
      fieldset: "brand",
      description: "Texto menor abaixo do título principal no hero.",
    }),
    defineField({
      name: "heroNote",
      title: "Linha de apoio do hero",
      type: "string",
      fieldset: "brand",
      description: "Frase curta de apoio que aparece no hero.",
    }),
    defineField({
      name: "heroImage",
      title: "Imagem do hero",
      type: "image",
      fieldset: "brand",
      description:
        "Imagem principal exibida no hero. Se não enviar, o site usa o visual padrão.",
      options: { hotspot: true },
      fields: [
        defineField({
          name: "alt",
          title: "Texto alternativo da imagem",
          type: "string",
          description: "Descrição da imagem para acessibilidade.",
        }),
      ],
    }),
    defineField({
      name: "brandTagline",
      title: "Tagline da marca",
      type: "string",
      fieldset: "brand",
      description: "Texto curto exibido no header, abaixo do nome da marca.",
    }),
    defineField({
      name: "fontVariant",
      title: "Estilo de fonte do site",
      type: "string",
      fieldset: "brand",
      description: "Escolha uma combinação tipográfica pronta para o site.",
      options: {
        list: [
          { title: "Clássico Script", value: "classic-script" },
          { title: "Vintage Marcante", value: "vintage-bold" },
          { title: "Editorial Limpo", value: "clean-editorial" },
          { title: "Oldschool Suave", value: "oldschool-soft" },
        ],
      },
      initialValue: "classic-script",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "themeVariant",
      title: "Paleta de cores do site",
      type: "string",
      fieldset: "brand",
      description: "Escolha uma paleta pronta para mudar o visual sem quebrar o design.",
      options: {
        list: [
          { title: "Clássico Rosé", value: "classic-rose" },
          { title: "Oliva Vintage", value: "olive-vintage" },
          { title: "Escuro Old School", value: "dark-oldschool" },
          { title: "Creme Rosado", value: "cream-pink" },
        ],
      },
      initialValue: "classic-rose",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "whatsapp",
      title: "WhatsApp",
      type: "string",
      fieldset: "contact",
      description: "Número com DDI/DDD. Exemplo: 5561999999999",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "instagram",
      title: "Instagram",
      type: "url",
      fieldset: "contact",
      description: "Link completo do Instagram da marca.",
      validation: (rule) => rule.uri({ scheme: ["http", "https"] }),
    }),
    defineField({
      name: "location",
      title: "Local de atendimento",
      type: "string",
      fieldset: "contact",
      description: "Texto exibido no bloco principal de contato.",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "contactDescription",
      title: "Descrição de contato",
      type: "text",
      rows: 4,
      fieldset: "contact",
      description: "Texto de apoio na seção de contato.",
    }),
    defineField({
      name: "contactActions",
      title: "Ações de contato",
      type: "array",
      fieldset: "contact",
      description: "Botões e mensagens exibidos no bloco de contato.",
      of: [
        defineField({
          name: "action",
          title: "Ação",
          type: "object",
          fields: [
            defineField({
              name: "label",
              title: "Texto do botão/linha",
              type: "string",
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: "href",
              title: "Link (opcional)",
              type: "string",
              description: "Se vazio, vira uma linha apenas informativa.",
            }),
            defineField({
              name: "messageOnly",
              title: "Somente mensagem",
              type: "boolean",
              description: "Marque quando não houver link clicável.",
              initialValue: false,
            }),
          ],
        }),
      ],
    }),
    defineField({
      name: "contactMainCtaText",
      title: "Texto do botão principal",
      type: "string",
      fieldset: "contact",
      description: "Texto do botão principal da seção de contato.",
    }),
    defineField({
      name: "contactFloatingText",
      title: "Texto do botão flutuante",
      type: "string",
      fieldset: "contact",
      description: "Texto do botão flutuante de WhatsApp.",
    }),
    defineField({
      name: "contactFloatingInstagramText",
      title: "Texto do botão flutuante do Instagram",
      type: "string",
      fieldset: "contact",
      description: "Texto do botão flutuante que leva para o Instagram.",
    }),
  ],
  preview: {
    prepare: () => ({
      title: "Configurações do site",
      subtitle: "Textos globais, contato, navegação e SEO",
    }),
  },
});
